### ISSUE TITLE
User Login: Set Up the Facebook SDK for JavaScript

### ISSUE THREAD

**Issue by Ghost---Shadow** [TechUniv2018/social-credit#3]
- Create Facebook App - obtain App ID and Secret
- Check for Login SDK
- Integrate API to friends' count (and other relevant parameters)
- Explore Passport JS or OAuth for Facebook login and session management.
- Cleanup login registration code

**Comment by googleknight** [comment]
[Done] Create Facebook App - obtain App ID and Secret
[Done] Check for Login SDK
[Done] Integrate API to friends' count (and other relevant parameters)
[Not Required] Explore Passport JS or OAuth for facebook login and session management.
[Done] Implemented Login page in  HTML/ CSS, welcomes user and shows count of friends, session is maintained by Facebook SDK. Implemented via JS methods in HTML file.
[Done] Implemented Facebook Login button in React.
